#  ___________________________
# /                |<13        \
#|     ____12>|   __ _____     |________
#|1   |       |10 ^^|      \            \
#|v_  |_______|v_ 11|_______\_______     \
#|    |<3           |<9      \      \    |
#|  __ _____4>|   __ _____14  \     |    |
#|  ^^|       |   ^^|     \v_  |___ /    |
#|  2 |       |6   7|     |    |<16      |
#|    |_______|v_   |_____/              |
#|                  |<8      __ ______  /
#|                           ^^|
# \_________5>|__ __________15/

#format: [left, forward, right]
"1": [["4","5",""],[3,4,0]]
"2": [["","12","4"],[0,5,2]]
"3": [["5","","12"],[4,0,4]]
"4": [["11","14","6"],[2,3,2]]
"5": [["7","15",""],[2,3,0]]
"6": [["15","","2"],[4,0,5]]
"7": [["3","11","14"],[3,2,3]]
"8": [["","2","7"],[0,4,2]]
"9": [["6","3","11"],[3,3,2]]
"10": [["14","6","3"],[3,2,3]]
"11": [["1","","16"],[5,0,9]]
"12": [["","16","10"],[0,10,2]]
"13": [["10","1",""],[2,5,0]]
"14": [["13","8",""],[11,3,0]]
"15": [["","9","13"],[0,3,11]]
"16": [["8","","9"],[3,0,3]]