# format: [time, velocity, angular vel]
turn_left: 
  - [0.6, 0.38, 0]
  - [0.6, 0.38, 2.5]
  - [0.3, 0.35, -0.05]
turn_right:
  - [0.4, 0.38, 0]
  - [0.8, 0.30,-2.8]
turn_forward:
  - [1.5, 0.45, 0.0]
