# format: [time, velocity, angular vel]
turn_left: 
  - [0.4, 0.38, 0]
  - [1.4, 0.38, 1.7]
  - [0.3, 0.35, 0.0]
turn_right:
  - [0.4, 0.38, 0]
  - [0.9, 0.30,-3.0]
  - [0.4, 0.38, 0.0]
turn_forward:
  - [1.5, 0.35, 0.0]
